LZW Compressor: lzw_v3.cpp File Reference
lzw_v3.cpp File Reference
LZW file compressor.
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <cstdlib>
#include <exception>
#include <fstream>
#include <ios>
#include <iostream>
#include <istream>
#include <limits>
#include <map>
#include <memory>
#include <ostream>
#include <stdexcept>
#include <string>
#include <utility>
#include <vector>
Typedefs
using CodeType = std::uint16_t
Type used to store and retrieve codes.
Functions
void compress (std::istream &is, std::ostream &os)
Compresses the contents of is and writes the result to os.
void decompress (std::istream &is, std::ostream &os)
Decompresses the contents of is and writes the result to os.
void print_usage (const std::string &s="", bool su=true)
Prints usage information and a custom error message.
int main (int argc, char *argv[])
Actual program entry point.
Variables
const CodeType globals::dms {std::numeric_limits<CodeType>::max()}
Dictionary Maximum Size (when reached, the dictionary will be reset)
Detailed Description
LZW file compressor.
Author
Julius Pettersson
Copyright
MIT/Expat License.
Version
3
This is the C++11 implementation of a Lempel-Ziv-Welch single-file command-line compressor. It uses the simpler fixed-width code compression method. It was written with Doxygen comments.
See Also
http://en.wikipedia.org/wiki/Lempel%E2%80%93Ziv%E2%80%93Welch
http://marknelson.us/2011/11/08/lzw-revisited/
http://www.cs.duke.edu/csed/curious/compression/lzw.html
http://warp.povusers.org/EfficientLZW/index.html
http://en.cppreference.com/
http://www.doxygen.org/
Definition in file lzw_v3.cpp.
Function Documentation
void compress (std::istream & is, std::ostream & os)
Compresses the contents of is and writes the result to os.
Parameters
[in] is input stream
[out] os output stream
Definition at line 53 of file lzw_v3.cpp.
Referenced by main().
 {
     std::map<std::pair<CodeType, char>, CodeType> dictionary;
     // "named" lambda function, used to reset the dictionary to its initial contents
     const auto reset_dictionary = [&dictionary] {
         dictionary.clear();
         const long int minc = std::numeric_limits<char>::min();
         const long int maxc = std::numeric_limits<char>::max();
         for (long int c = minc; c <= maxc; ++c)
         {
             // to prevent Undefined Behavior, resulting from reading and modifying
             // the dictionary object at the same time
             const CodeType dictionary_size = dictionary.size();
             dictionary[{globals::dms, static_cast<char> (c)}] = dictionary_size;
         }
     };
     reset_dictionary();
     CodeType i {globals::dms}; // Index
     char c;
     while (is.get(c))
     {
         // dictionary's maximum size was reached
         if (dictionary.size() == globals::dms)
             reset_dictionary();
         if (dictionary.count({i, c}) == 0)
         {
             // to prevent Undefined Behavior, resulting from reading and modifying
             // the dictionary object at the same time
             const CodeType dictionary_size = dictionary.size();
             dictionary[{i, c}] = dictionary_size;
             os.write(reinterpret_cast<const char *> (&i), sizeof (CodeType));
             i = dictionary.at({globals::dms, c});
         }
         else
             i = dictionary.at({i, c});
     }
     if (i != globals::dms)
         os.write(reinterpret_cast<const char *> (&i), sizeof (CodeType));
 }
void decompress (std::istream & is, std::ostream & os)
Decompresses the contents of is and writes the result to os.
Parameters
[in] is input stream
[out] os output stream
Definition at line 108 of file lzw_v3.cpp.
Referenced by main().
 {
     std::vector<std::pair<CodeType, char>> dictionary;
     // "named" lambda function, used to reset the dictionary to its initial contents
     const auto reset_dictionary = [&dictionary] {
         dictionary.clear();
         dictionary.reserve(globals::dms);
         const long int minc = std::numeric_limits<char>::min();
         const long int maxc = std::numeric_limits<char>::max();
         for (long int c = minc; c <= maxc; ++c)
             dictionary.push_back({globals::dms, static_cast<char> (c)});
     };
     const auto rebuild_string = [&dictionary](CodeType k) -> std::vector<char> {
         std::vector<char> s; // String
         while (k != globals::dms)
         {
             s.push_back(dictionary.at(k).second);
             k = dictionary.at(k).first;
         }
         std::reverse(s.begin(), s.end());
         return s;
     };
     reset_dictionary();
     CodeType i {globals::dms}; // Index
     CodeType k; // Key
     while (is.read(reinterpret_cast<char *> (&k), sizeof (CodeType)))
     {
         // dictionary's maximum size was reached
         if (dictionary.size() == globals::dms)
             reset_dictionary();
         if (k > dictionary.size())
             throw std::runtime_error("invalid compressed code");
         std::vector<char> s; // String
         if (k == dictionary.size())
         {
             dictionary.push_back({i, rebuild_string(i).front()});
             s = rebuild_string(k);
         }
         else
         {
             s = rebuild_string(k);
             if (i != globals::dms)
                 dictionary.push_back({i, s.front()});
         }
         os.write(&s.front(), s.size());
         i = k;
     }
     if (!is.eof() || is.gcount() != 0)
         throw std::runtime_error("corrupted compressed file");
 }
int main (int argc, char * argv[])
Actual program entry point.
Parameters
argc number of command line arguments
[in] argv array of command line arguments
Return values
EXIT_FAILURE for failed operation
EXIT_SUCCESS for successful operation
Definition at line 205 of file lzw_v3.cpp.
References compress(), decompress(), and print_usage().
 {
     if (argc != 4)
     {
         print_usage("Wrong number of arguments.");
         return EXIT_FAILURE;
     }
     enum class Mode {
         Compress,
         Decompress
     };
     Mode m;
     if (std::string(argv[1]) == "-c")
         m = Mode::Compress;
     else
     if (std::string(argv[1]) == "-d")
         m = Mode::Decompress;
     else
     {
         print_usage(std::string("flag `") + argv[1] + "' is not recognized.");
         return EXIT_FAILURE;
     }
     const std::size_t buffer_size {1024 * 1024};
     // these custom buffers should be larger than the default ones
     const std::unique_ptr<char[]> input_buffer(new char[buffer_size]);
     const std::unique_ptr<char[]> output_buffer(new char[buffer_size]);
     std::ifstream input_file;
     std::ofstream output_file;
     input_file.rdbuf()->pubsetbuf(input_buffer.get(), buffer_size);
     input_file.open(argv[2], std::ios_base::binary);
     if (!input_file.is_open())
     {
         print_usage(std::string("input_file `") + argv[2] + "' could not be opened.");
         return EXIT_FAILURE;
     }
     output_file.rdbuf()->pubsetbuf(output_buffer.get(), buffer_size);
     output_file.open(argv[3], std::ios_base::binary);
     if (!output_file.is_open())
     {
         print_usage(std::string("output_file `") + argv[3] + "' could not be opened.");
         return EXIT_FAILURE;
     }
     try
     {
         input_file.exceptions(std::ios_base::badbit);
         output_file.exceptions(std::ios_base::badbit | std::ios_base::failbit);
         if (m == Mode::Compress)
             compress(input_file, output_file);
         else
         if (m == Mode::Decompress)
             decompress(input_file, output_file);
     }
     catch (const std::ios_base::failure &f)
     {
         print_usage(std::string("File input/output failure: ") + f.what() + '.', false);
         return EXIT_FAILURE;
     }
     catch (const std::exception &e)
     {
         print_usage(std::string("Caught exception: ") + e.what() + '.', false);
         return EXIT_FAILURE;
     }
     return EXIT_SUCCESS;
 }
void print_usage (const std::string & s = "", bool su = true)
Prints usage information and a custom error message.
Parameters
s custom error message to be printed
su Show Usage information
Definition at line 179 of file lzw_v3.cpp.
Referenced by main().
 {
     if (!s.empty())
         std::cerr << "\nERROR: " << s << '\n';
     if (su)
     {
         std::cerr << "\nUsage:\n";
         std::cerr << "\tprogram -flag input_file output_file\n\n";
         std::cerr << "Where `flag' is either `c' for compressing, or `d' for decompressing, and\n";
         std::cerr << "`input_file' and `output_file' are distinct files.\n\n";
         std::cerr << "Examples:\n";
         std::cerr << "\tlzw_v3.exe -c license.txt license.lzw\n";
         std::cerr << "\tlzw_v3.exe -d license.lzw new_license.txt\n";
     }
     std::cerr << std::endl;
 }